# Generated by Django 2.2.5 on 2021-02-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_toner_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
