# Generated by Django 2.2.5 on 2021-02-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_auto_20210215_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='info',
            field=models.TextField(default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Toner Modeli'),
        ),
    ]
