# Generated by Django 2.2.5 on 2021-02-15 12:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='İsim Soyisim')),
                ('company_name', models.CharField(max_length=100, verbose_name='Firma')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numaranız')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-Mail Adresiniz')),
                ('content', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
        ),
    ]
