# Generated by Django 2.2.5 on 2021-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210216_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.AddField(
            model_name='service',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='İsim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Soyisim'),
            preserve_default=False,
        ),
    ]
