# Generated by Django 2.2.5 on 2021-02-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210219_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
