# Generated by Django 2.2.5 on 2021-02-15 11:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='İsim Soyisim')),
                ('company_name', models.CharField(max_length=100, verbose_name='Şirket İsmi')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='İletişim Numaranız', max_length=31)),
                ('mail', models.EmailField(max_length=254, verbose_name='E-Mail Adresiniz')),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
