# Generated by Django 2.2.5 on 2021-02-15 12:00

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numaranız'),
        ),
    ]
