# Generated by Django 2.2.5 on 2021-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20210215_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Açıklama'),
        ),
    ]
