# Generated by Django 2.2.5 on 2021-02-19 11:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Marka')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='deneme', max_length=50, verbose_name='İsim')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Soyisim')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Firma')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefon Numaranız')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Adresiniz')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('brand_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='akar.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyisim')),
                ('company_name', models.CharField(max_length=100, verbose_name='Firma')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numaranız')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-Mail Adresiniz')),
                ('content', models.TextField(max_length=1000, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akar.Brand')),
            ],
        ),
    ]
