# Generated by Django 2.2.5 on 2021-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_name',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='İsim Soyisim'),
            preserve_default=False,
        ),
    ]
