# Generated by Django 2.2.5 on 2021-02-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akar', '0002_auto_20210219_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
