# Generated by Django 2.2.5 on 2021-02-22 14:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('akar', '0004_auto_20210219_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='submodel',
            field=models.CharField(default=1, max_length=50, verbose_name='Cihazınızın Modeli'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akar.Brand', verbose_name='Cihazınızın Markası'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firma İsmi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numarası'),
        ),
    ]
