# Generated by Django 2.2.5 on 2021-02-26 06:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('akar', '0005_auto_20210222_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='last_name',
        ),
        migrations.AddField(
            model_name='demand',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='İsim Soyisim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demand',
            name='product',
            field=models.CharField(default=1, max_length=50, verbose_name='Teklif Almak İstediğiniz Ürün'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demand',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miktar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demand',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firma İsmi'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='content',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='service',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='akar.Brand', verbose_name='Cihazınızın Markası'),
        ),
    ]
