# Generated by Django 2.2.5 on 2021-03-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akar', '0012_auto_20210305_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='agent',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Temsilci'),
        ),
        migrations.AlterField(
            model_name='service',
            name='agent',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Temsilci'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
